apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-webapp
spec:
  ingressClassName: nginx
  rules:
  - host: "webapp.info"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: webapp-service
            port:
              number: 3000