# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: webapp-ingress
# spec:
#   ingressClassName: nginx
#   rules:
#     - host: localhost
#       http:
#         paths:
#         - path: /
#           pathType: Prefix
#           backend:
#             service:
#               name: webapp-service
#               port:
#                 number: 8090
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  webapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
     paths:
     - path: : /
        pathType: webapp-service
        backend:
          serviceName: web
          servicePort: 8090